### ISSUE TITLE
Error: font loader not implemented

### ISSUE THREAD

**Issue by AlfredOdling** [dai-shi/react-native-dom-expo#5]
First of all, great initiative.
I built and ran the project and it works fine on iOS but in rndom I get the following message:

<img width="650" alt="skarmavbild 2019-03-01 kl 07 37 13" src="https://user-images.githubusercontent.com/18306386/53620919-09dcc380-3bf5-11e9-9d54-b20bca3aad22.png">

**Comment by dai-shi** [comment]
Hi! Thanks for trying out.
I've already filed the issue #3, so let me merge it. (closing this one, and add a note in the other)
